### ISSUE TITLE
Is iPhone only for iPhone or for other apple devices too?

### ISSUE THREAD

**Issue by JamieDixon** [ConnectedHomes/hivehome-webapp-favicons-webpack-plugin#4]
I'm wondering how we can use this lib for iPad etc. Is iPhone config iOS config or is it specific to the iPhone device?

**Comment by beavis07** [comment]
Should be standard across all the ios devices... probably kinda poorly named, huh?

Worth changing the config keys to `ios` do you think?

**Comment by JamieDixon** [comment]
Sounds like a plan. I might take this one to get some exp with this lib. Ok with you? I'll raise a PR with the changes when I'm done.

**Comment by beavis07** [comment]
Yes please mate! Thanks :+1:
